spring:
  application:
    name: application-tracker-service
  datasource:
    url: jdbc:postgresql://localhost:5432/applicationtracker
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format-sql: true


  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
server:
  port: 8082

app:
  jwt:
    secret: ${JWT_SECRET}
    expiration: 86400000
  services:
    match-service-url: http://localhost:8083
